services:
  quarkus:
    build:
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
  rabbitmq:
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  smtp:
    image: soulteary/maildev
    ports:
      - 1080:1080
      - 1025:1025